name: Auto Labeling

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
  discussion:
    types:
      - created

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Auto Labeling with ChatGPT
        uses: nikpivkin/auto-label@v0.0.2
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          details: "Our product is an GitHub action that uses ChatGPT to automatically assign labels to github issues, discussions and PRs based on their title and content."
          excluded-labels: "duplicate"
