name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/auto-labeling.yaml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/auto-labeling.yaml'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Run unit tests
      run: go test -v ./...

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . --file Dockerfile --platform linux/amd64 --tag auto-label:"$(date +%s)"
